services:
  dex:
    image: ghcr.io/dexidp/dex:v2.39.1
    container_name: identity-provider
    restart: unless-stopped
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    volumes:
      - ./dex/config.yaml:/etc/dex/config.yaml:ro
    networks:
      - infra-net

networks:
  infra-net:
    external: true
